name: ClickHouse Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      clickhouse:
        image: clickhouse/clickhouse-server:latest
        ports:
          - 9000:9000
          - 8123:8123
        options: --health-cmd "curl --silent --fail http://localhost:8123/ping" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ClickHouse client
        run: sudo apt-get install -y clickhouse-client

      - name: Run ClickHouse queries
        run: |
          clickhouse-client --query "CREATE TABLE IF NOT EXISTS test_table (id UInt32, name String) ENGINE = Log;"
          clickhouse-client --query "INSERT INTO test_table VALUES (1, 'Hello, ClickHouse!');"
          clickhouse-client --query "SELECT * FROM test_table;"
